packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'packages/shared/*'
  - 'packages/extensions/*'
  # all packages in subdirs of components/
  # - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
